apiVersion: v1alpha1
kind: Role
metadata:
  name: plugin-oauth-role-template
  labels:
    halo.run/hidden: "false"
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-authenticated: "true"
  annotations:
    rbac.authorization.halo.run/module: "Authentication"
    rbac.authorization.halo.run/display-name: "OAuth2 AccessRole"
rules:
  - apiGroups: [ "api.plugin.halo.run" ]
    resourceNames: [ "plugin-oauth2" ]
    resources: [ "plugins/connect", "plugins/disconnect","plugins/wechat/checkMsg"]
    verbs: [ "create", "get","list", "update" ]
  - nonResourceURLs: [ "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/loginQrCode" , "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/userLogin" , "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/wechat/check"]
    verbs: ["get","update" ]
#  - nonResourceURLs: [ "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/wechat/checkMsg" ]
#    verbs: ["create"]
